source 'https://github.com/nscribble/htSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

platform :ios, '8.0'

target 'HLTStoreKit_Example' do
  pod 'HLTStoreKit', :path => '../'
#  pod 'HLTAPIClient'

  target 'HLTStoreKit_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  end
end
